#!/bin/bash

# Initialize Keyring
pacman-key --init
pacman-key --populate
pacman -Sy archlinux-keyring --noconfirm
pacman -Su --noconfirm

# Clean Packages
pacman -Syyu bat git lsd neofetch neovim nodejs npm python tree wget --noconfirm
pacman -Runs vim nano --noconfirm

# Install Oh My Posh
wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
chmod +x /usr/local/bin/oh-my-posh

# Download Dotfiles
wget https://raw.githubusercontent.com/Rakioth/Dotfiles/main/helpers/.bashrc -O /home/raks/.bashrc
wget --directory-prefix=/home/raks/.config/nvim/ https://raw.githubusercontent.com/Rakioth/Dotfiles/main/helpers/init.vim

# Create Symlinks
ln -s /home/raks/.bashrc /root/.bashrc
ln -s /home/raks/.config /root/.config