#!/bin/bash

pacman-key --init
pacman-key --populate
pacman -Sy archlinux-keyring --noconfirm
pacman -Su --noconfirm
pacman -Syyu bat git lsd neofetch neovim nodejs npm python tree wget --noconfirm
pacman -Runs vim nano --noconfirm
wget https://raw.githubusercontent.com/Rakioth/Dotfiles/main/helpers/.bashrc -O /home/raks/.bashrc
wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
chmod +x /usr/local/bin/oh-my-posh
ln -s /home/raks/.bashrc /root/.bashrc
wget --directory-prefix=/home/raks/.config/nvim/ https://raw.githubusercontent.com/Rakioth/Dotfiles/main/helpers/init.vim