#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"

. "$env:DOTFILES\core\main.ps1"

Util-Service -Name "AJRouter"                                 -StartupType Disabled
Util-Service -Name "ALG"                                      -StartupType Manual
Util-Service -Name "AppIDSvc"                                 -StartupType Manual
Util-Service -Name "AppMgmt"                                  -StartupType Manual
Util-Service -Name "AppReadiness"                             -StartupType Manual
Util-Service -Name "AppVClient"                               -StartupType Disabled
Util-Service -Name "AppXSvc"                                  -StartupType Manual
Util-Service -Name "Appinfo"                                  -StartupType Manual
Util-Service -Name "AssignedAccessManagerSvc"                 -StartupType Disabled
Util-Service -Name "AudioEndpointBuilder"                     -StartupType Automatic
Util-Service -Name "AudioSrv"                                 -StartupType Automatic
Util-Service -Name "Audiosrv"                                 -StartupType Automatic
Util-Service -Name "AxInstSV"                                 -StartupType Manual
Util-Service -Name "BDESVC"                                   -StartupType Manual
Util-Service -Name "BFE"                                      -StartupType Automatic
Util-Service -Name "BITS"                                     -StartupType AutomaticDelayedStart
Util-Service -Name "BTAGService"                              -StartupType Manual
Util-Service -Name "BcastDVRUserService_*"                    -StartupType Manual
Util-Service -Name "BluetoothUserService_*"                   -StartupType Manual
Util-Service -Name "BrokerInfrastructure"                     -StartupType Automatic
Util-Service -Name "Browser"                                  -StartupType Manual
Util-Service -Name "BthAvctpSvc"                              -StartupType Automatic
Util-Service -Name "BthHFSrv"                                 -StartupType Automatic
Util-Service -Name "CDPSvc"                                   -StartupType Manual
Util-Service -Name "CDPUserSvc_*"                             -StartupType Automatic
Util-Service -Name "COMSysApp"                                -StartupType Manual
Util-Service -Name "CaptureService_*"                         -StartupType Manual
Util-Service -Name "CertPropSvc"                              -StartupType Manual
Util-Service -Name "ClipSVC"                                  -StartupType Manual
Util-Service -Name "ConsentUxUserSvc_*"                       -StartupType Manual
Util-Service -Name "CoreMessagingRegistrar"                   -StartupType Automatic
Util-Service -Name "CredentialEnrollmentManagerUserSvc_*"     -StartupType Manual
Util-Service -Name "CryptSvc"                                 -StartupType Automatic
Util-Service -Name "CscService"                               -StartupType Manual
Util-Service -Name "DPS"                                      -StartupType Automatic
Util-Service -Name "DcomLaunch"                               -StartupType Automatic
Util-Service -Name "DcpSvc"                                   -StartupType Manual
Util-Service -Name "DevQueryBroker"                           -StartupType Manual
Util-Service -Name "DeviceAssociationBrokerSvc_*"             -StartupType Manual
Util-Service -Name "DeviceAssociationService"                 -StartupType Manual
Util-Service -Name "DeviceInstall"                            -StartupType Manual
Util-Service -Name "DevicePickerUserSvc_*"                    -StartupType Manual
Util-Service -Name "DevicesFlowUserSvc_*"                     -StartupType Manual
Util-Service -Name "Dhcp"                                     -StartupType Automatic
Util-Service -Name "DiagTrack"                                -StartupType Disabled
Util-Service -Name "DialogBlockingService"                    -StartupType Disabled
Util-Service -Name "DispBrokerDesktopSvc"                     -StartupType Automatic
Util-Service -Name "DisplayEnhancementService"                -StartupType Manual
Util-Service -Name "DmEnrollmentSvc"                          -StartupType Manual
Util-Service -Name "Dnscache"                                 -StartupType Automatic
Util-Service -Name "DoSvc"                                    -StartupType AutomaticDelayedStart
Util-Service -Name "DsSvc"                                    -StartupType Manual
Util-Service -Name "DsmSvc"                                   -StartupType Manual
Util-Service -Name "DusmSvc"                                  -StartupType Automatic
Util-Service -Name "EFS"                                      -StartupType Manual
Util-Service -Name "EapHost"                                  -StartupType Manual
Util-Service -Name "EntAppSvc"                                -StartupType Manual
Util-Service -Name "EventLog"                                 -StartupType Automatic
Util-Service -Name "EventSystem"                              -StartupType Automatic
Util-Service -Name "FDResPub"                                 -StartupType Manual
Util-Service -Name "Fax"                                      -StartupType Manual
Util-Service -Name "FontCache"                                -StartupType Automatic
Util-Service -Name "FrameServer"                              -StartupType Manual
Util-Service -Name "FrameServerMonitor"                       -StartupType Manual
Util-Service -Name "GraphicsPerfSvc"                          -StartupType Manual
Util-Service -Name "HomeGroupListener"                        -StartupType Manual
Util-Service -Name "HomeGroupProvider"                        -StartupType Manual
Util-Service -Name "HvHost"                                   -StartupType Manual
Util-Service -Name "IEEtwCollectorService"                    -StartupType Manual
Util-Service -Name "IKEEXT"                                   -StartupType Manual
Util-Service -Name "InstallService"                           -StartupType Manual
Util-Service -Name "InventorySvc"                             -StartupType Manual
Util-Service -Name "IpxlatCfgSvc"                             -StartupType Manual
Util-Service -Name "KeyIso"                                   -StartupType Automatic
Util-Service -Name "KtmRm"                                    -StartupType Manual
Util-Service -Name "LSM"                                      -StartupType Automatic
Util-Service -Name "LanmanServer"                             -StartupType Automatic
Util-Service -Name "LanmanWorkstation"                        -StartupType Automatic
Util-Service -Name "LicenseManager"                           -StartupType Manual
Util-Service -Name "LxpSvc"                                   -StartupType Manual
Util-Service -Name "MSDTC"                                    -StartupType Manual
Util-Service -Name "MSiSCSI"                                  -StartupType Manual
Util-Service -Name "MapsBroker"                               -StartupType AutomaticDelayedStart
Util-Service -Name "McpManagementService"                     -StartupType Manual
Util-Service -Name "MessagingService_*"                       -StartupType Manual
Util-Service -Name "MicrosoftEdgeElevationService"            -StartupType Manual
Util-Service -Name "MixedRealityOpenXRSvc"                    -StartupType Manual
Util-Service -Name "MpsSvc"                                   -StartupType Automatic
Util-Service -Name "MsKeyboardFilter"                         -StartupType Manual
Util-Service -Name "NPSMSvc_*"                                -StartupType Manual
Util-Service -Name "NaturalAuthentication"                    -StartupType Manual
Util-Service -Name "NcaSvc"                                   -StartupType Manual
Util-Service -Name "NcbService"                               -StartupType Manual
Util-Service -Name "NcdAutoSetup"                             -StartupType Manual
Util-Service -Name "NetSetupSvc"                              -StartupType Manual
Util-Service -Name "NetTcpPortSharing"                        -StartupType Disabled
Util-Service -Name "Netlogon"                                 -StartupType Automatic
Util-Service -Name "Netman"                                   -StartupType Manual
Util-Service -Name "NgcCtnrSvc"                               -StartupType Manual
Util-Service -Name "NgcSvc"                                   -StartupType Manual
Util-Service -Name "NlaSvc"                                   -StartupType Manual
Util-Service -Name "OneSyncSvc_*"                             -StartupType Automatic
Util-Service -Name "P9RdrService_*"                           -StartupType Manual
Util-Service -Name "PNRPAutoReg"                              -StartupType Manual
Util-Service -Name "PNRPsvc"                                  -StartupType Manual
Util-Service -Name "PcaSvc"                                   -StartupType Manual
Util-Service -Name "PeerDistSvc"                              -StartupType Manual
Util-Service -Name "PenService_*"                             -StartupType Manual
Util-Service -Name "PerfHost"                                 -StartupType Manual
Util-Service -Name "PhoneSvc"                                 -StartupType Manual
Util-Service -Name "PimIndexMaintenanceSvc_*"                 -StartupType Manual
Util-Service -Name "PlugPlay"                                 -StartupType Manual
Util-Service -Name "PolicyAgent"                              -StartupType Manual
Util-Service -Name "Power"                                    -StartupType Automatic
Util-Service -Name "PrintNotify"                              -StartupType Manual
Util-Service -Name "PrintWorkflowUserSvc_*"                   -StartupType Manual
Util-Service -Name "ProfSvc"                                  -StartupType Automatic
Util-Service -Name "PushToInstall"                            -StartupType Manual
Util-Service -Name "QWAVE"                                    -StartupType Manual
Util-Service -Name "RasAuto"                                  -StartupType Manual
Util-Service -Name "RasMan"                                   -StartupType Manual
Util-Service -Name "RemoteAccess"                             -StartupType Disabled
Util-Service -Name "RemoteRegistry"                           -StartupType Disabled
Util-Service -Name "RetailDemo"                               -StartupType Manual
Util-Service -Name "RmSvc"                                    -StartupType Manual
Util-Service -Name "RpcEptMapper"                             -StartupType Automatic
Util-Service -Name "RpcLocator"                               -StartupType Manual
Util-Service -Name "RpcSs"                                    -StartupType Automatic
Util-Service -Name "SCPolicySvc"                              -StartupType Manual
Util-Service -Name "SCardSvr"                                 -StartupType Manual
Util-Service -Name "SDRSVC"                                   -StartupType Manual
Util-Service -Name "SEMgrSvc"                                 -StartupType Manual
Util-Service -Name "SENS"                                     -StartupType Automatic
Util-Service -Name "SNMPTRAP"                                 -StartupType Manual
Util-Service -Name "SNMPTrap"                                 -StartupType Manual
Util-Service -Name "SSDPSRV"                                  -StartupType Manual
Util-Service -Name "SamSs"                                    -StartupType Automatic
Util-Service -Name "ScDeviceEnum"                             -StartupType Manual
Util-Service -Name "Schedule"                                 -StartupType Automatic
Util-Service -Name "SecurityHealthService"                    -StartupType Manual
Util-Service -Name "Sense"                                    -StartupType Manual
Util-Service -Name "SensorDataService"                        -StartupType Manual
Util-Service -Name "SensorService"                            -StartupType Manual
Util-Service -Name "SensrSvc"                                 -StartupType Manual
Util-Service -Name "SessionEnv"                               -StartupType Manual
Util-Service -Name "SgrmBroker"                               -StartupType Automatic
Util-Service -Name "SharedAccess"                             -StartupType Manual
Util-Service -Name "SharedRealitySvc"                         -StartupType Manual
Util-Service -Name "ShellHWDetection"                         -StartupType Automatic
Util-Service -Name "SmsRouter"                                -StartupType Manual
Util-Service -Name "Spooler"                                  -StartupType Automatic
Util-Service -Name "SstpSvc"                                  -StartupType Manual
Util-Service -Name "StateRepository"                          -StartupType Manual
Util-Service -Name "StiSvc"                                   -StartupType Manual
Util-Service -Name "StorSvc"                                  -StartupType Manual
Util-Service -Name "SysMain"                                  -StartupType Automatic
Util-Service -Name "SystemEventsBroker"                       -StartupType Automatic
Util-Service -Name "TabletInputService"                       -StartupType Manual
Util-Service -Name "TapiSrv"                                  -StartupType Manual
Util-Service -Name "TermService"                              -StartupType Automatic
Util-Service -Name "TextInputManagementService"               -StartupType Manual
Util-Service -Name "Themes"                                   -StartupType Automatic
Util-Service -Name "TieringEngineService"                     -StartupType Manual
Util-Service -Name "TimeBroker"                               -StartupType Manual
Util-Service -Name "TimeBrokerSvc"                            -StartupType Manual
Util-Service -Name "TokenBroker"                              -StartupType Manual
Util-Service -Name "TrkWks"                                   -StartupType Automatic
Util-Service -Name "TroubleshootingSvc"                       -StartupType Manual
Util-Service -Name "TrustedInstaller"                         -StartupType Manual
Util-Service -Name "UI0Detect"                                -StartupType Manual
Util-Service -Name "UdkUserSvc_*"                             -StartupType Manual
Util-Service -Name "UevAgentService"                          -StartupType Disabled
Util-Service -Name "UmRdpService"                             -StartupType Manual
Util-Service -Name "UnistoreSvc_*"                            -StartupType Manual
Util-Service -Name "UserDataSvc_*"                            -StartupType Manual
Util-Service -Name "UserManager"                              -StartupType Automatic
Util-Service -Name "UsoSvc"                                   -StartupType Manual
Util-Service -Name "VGAuthService"                            -StartupType Automatic
Util-Service -Name "VMTools"                                  -StartupType Automatic
Util-Service -Name "VSS"                                      -StartupType Manual
Util-Service -Name "VacSvc"                                   -StartupType Manual
Util-Service -Name "VaultSvc"                                 -StartupType Automatic
Util-Service -Name "W32Time"                                  -StartupType Manual
Util-Service -Name "WEPHOSTSVC"                               -StartupType Manual
Util-Service -Name "WFDSConMgrSvc"                            -StartupType Manual
Util-Service -Name "WMPNetworkSvc"                            -StartupType Manual
Util-Service -Name "WManSvc"                                  -StartupType Manual
Util-Service -Name "WPDBusEnum"                               -StartupType Manual
Util-Service -Name "WSService"                                -StartupType Manual
Util-Service -Name "WSearch"                                  -StartupType AutomaticDelayedStart
Util-Service -Name "WaaSMedicSvc"                             -StartupType Manual
Util-Service -Name "WalletService"                            -StartupType Manual
Util-Service -Name "WarpJITSvc"                               -StartupType Manual
Util-Service -Name "WbioSrvc"                                 -StartupType Manual
Util-Service -Name "Wcmsvc"                                   -StartupType Automatic
Util-Service -Name "WcsPlugInService"                         -StartupType Manual
Util-Service -Name "WdNisSvc"                                 -StartupType Manual
Util-Service -Name "WdiServiceHost"                           -StartupType Manual
Util-Service -Name "WdiSystemHost"                            -StartupType Manual
Util-Service -Name "WebClient"                                -StartupType Manual
Util-Service -Name "Wecsvc"                                   -StartupType Manual
Util-Service -Name "WerSvc"                                   -StartupType Manual
Util-Service -Name "WiaRpc"                                   -StartupType Manual
Util-Service -Name "WinDefend"                                -StartupType Automatic
Util-Service -Name "WinHttpAutoProxySvc"                      -StartupType Manual
Util-Service -Name "WinRM"                                    -StartupType Manual
Util-Service -Name "Winmgmt"                                  -StartupType Automatic
Util-Service -Name "WlanSvc"                                  -StartupType Automatic
Util-Service -Name "WpcMonSvc"                                -StartupType Manual
Util-Service -Name "WpnService"                               -StartupType Manual
Util-Service -Name "WpnUserService_*"                         -StartupType Automatic
Util-Service -Name "WwanSvc"                                  -StartupType Manual
Util-Service -Name "XblAuthManager"                           -StartupType Manual
Util-Service -Name "XblGameSave"                              -StartupType Manual
Util-Service -Name "XboxGipSvc"                               -StartupType Manual
Util-Service -Name "XboxNetApiSvc"                            -StartupType Manual
Util-Service -Name "autotimesvc"                              -StartupType Manual
Util-Service -Name "bthserv"                                  -StartupType Manual
Util-Service -Name "camsvc"                                   -StartupType Manual
Util-Service -Name "cbdhsvc_*"                                -StartupType Manual
Util-Service -Name "cloudidsvc"                               -StartupType Manual
Util-Service -Name "dcsvc"                                    -StartupType Manual
Util-Service -Name "defragsvc"                                -StartupType Manual
Util-Service -Name "diagnosticshub.standardcollector.service" -StartupType Manual
Util-Service -Name "diagsvc"                                  -StartupType Manual
Util-Service -Name "dmwappushservice"                         -StartupType Manual
Util-Service -Name "dot3svc"                                  -StartupType Manual
Util-Service -Name "edgeupdate"                               -StartupType Manual
Util-Service -Name "edgeupdatem"                              -StartupType Manual
Util-Service -Name "embeddedmode"                             -StartupType Manual
Util-Service -Name "fdPHost"                                  -StartupType Manual
Util-Service -Name "fhsvc"                                    -StartupType Manual
Util-Service -Name "gpsvc"                                    -StartupType Automatic
Util-Service -Name "hidserv"                                  -StartupType Manual
Util-Service -Name "icssvc"                                   -StartupType Manual
Util-Service -Name "iphlpsvc"                                 -StartupType Automatic
Util-Service -Name "lfsvc"                                    -StartupType Manual
Util-Service -Name "lltdsvc"                                  -StartupType Manual
Util-Service -Name "lmhosts"                                  -StartupType Manual
Util-Service -Name "mpssvc"                                   -StartupType Automatic
Util-Service -Name "msiserver"                                -StartupType Manual
Util-Service -Name "netprofm"                                 -StartupType Manual
Util-Service -Name "nsi"                                      -StartupType Automatic
Util-Service -Name "p2pimsvc"                                 -StartupType Manual
Util-Service -Name "p2psvc"                                   -StartupType Manual
Util-Service -Name "perceptionsimulation"                     -StartupType Manual
Util-Service -Name "pla"                                      -StartupType Manual
Util-Service -Name "seclogon"                                 -StartupType Manual
Util-Service -Name "shpamsvc"                                 -StartupType Disabled
Util-Service -Name "smphost"                                  -StartupType Manual
Util-Service -Name "spectrum"                                 -StartupType Manual
Util-Service -Name "sppsvc"                                   -StartupType AutomaticDelayedStart
Util-Service -Name "ssh-agent"                                -StartupType Disabled
Util-Service -Name "svsvc"                                    -StartupType Manual
Util-Service -Name "swprv"                                    -StartupType Manual
Util-Service -Name "tiledatamodelsvc"                         -StartupType Automatic
Util-Service -Name "tzautoupdate"                             -StartupType Disabled
Util-Service -Name "uhssvc"                                   -StartupType Disabled
Util-Service -Name "upnphost"                                 -StartupType Manual
Util-Service -Name "vds"                                      -StartupType Manual
Util-Service -Name "vm3dservice"                              -StartupType Manual
Util-Service -Name "vmicguestinterface"                       -StartupType Manual
Util-Service -Name "vmicheartbeat"                            -StartupType Manual
Util-Service -Name "vmickvpexchange"                          -StartupType Manual
Util-Service -Name "vmicrdv"                                  -StartupType Manual
Util-Service -Name "vmicshutdown"                             -StartupType Manual
Util-Service -Name "vmictimesync"                             -StartupType Manual
Util-Service -Name "vmicvmsession"                            -StartupType Manual
Util-Service -Name "vmicvss"                                  -StartupType Manual
Util-Service -Name "vmvss"                                    -StartupType Manual
Util-Service -Name "wbengine"                                 -StartupType Manual
Util-Service -Name "wcncsvc"                                  -StartupType Manual
Util-Service -Name "webthreatdefsvc"                          -StartupType Manual
Util-Service -Name "webthreatdefusersvc_*"                    -StartupType Automatic
Util-Service -Name "wercplsupport"                            -StartupType Manual
Util-Service -Name "wisvc"                                    -StartupType Manual
Util-Service -Name "wlidsvc"                                  -StartupType Manual
Util-Service -Name "wlpasvc"                                  -StartupType Manual
Util-Service -Name "wmiApSrv"                                 -StartupType Manual
Util-Service -Name "workfolderssvc"                           -StartupType Manual
Util-Service -Name "wscsvc"                                   -StartupType AutomaticDelayedStart
Util-Service -Name "wuauserv"                                 -StartupType Manual
Util-Service -Name "wudfsvc"                                  -StartupType Manual
